import { AudioBitrate } from '_shared/enums/AudioBitrate';
import { AudioProcessorType } from '_shared/enums/AudioProcessorType';
import { BridgeMode } from '_shared/enums/BridgeMode';
import { VideoBitrate } from '_shared/enums/VideoBitrate';
import { VideoCodec } from '_shared/enums/VideoCodec';
import { VideoResolution } from '_shared/enums/VideoResolution';

export interface SettingsState {
  allowUntrustedSSL: boolean;
  audioBitrate: AudioBitrate;
  audioProcessorControlsEnabled: boolean;
  audioProcessorIp: string;
  audioProcessorType: AudioProcessorType;
  autostartBroadcastsEnabled: boolean;
  bridgeMode: BridgeMode;
  broadcastsKey: string;
  broadcastsServer: string;
  communicationAuthenticationEnabled: boolean;
  communicationBridgeToken: string;
  communicationBridgeUrl: string;
  communicationCameraEnabled: boolean;
  communicationMicrophoneEnabled: boolean;
  contentProtectionDisabled: boolean;
  daysToKeepData: number;
  deleteAfterUpload: boolean;
  dualCamModeEnabled: boolean;
  kalturaTrustedCA: string;
  meetTrustedCA: string;
  mirrorCamera: boolean;
  moodleEnabled: boolean;
  moodlePlayerId: number;
  moodleToken: string;
  moodleTrustedCA: string;
  moodleUrl: string;
  presenceControlEnabled: boolean;
  ptzCameraControlsEnabled: boolean;
  ptzCameraDefaultPresetIndex: number;
  ptzCameraIp: string;
  reactivateSchedule: boolean;
  recordingPath: string;
  resetPtzCameraPreset: boolean;
  sakaiEnabled: boolean;
  sakaiLogin: string;
  sakaiPassword: string;
  sakaiTrustedCA: string;
  sakaiUrl: string;
  scheduleCommunicationEnabled: boolean;
  scheduleEnabled: boolean;
  scheduleRoomNumber: string;
  scheduleToken: string;
  scheduleTrustedCA: string;
  scheduleUrl: string;
  servicePartnerId: number;
  servicePartnerSecret: string;
  serviceTokenId: string;
  serviceTokenSecret: string;
  serviceUrl: string;
  videoBitrate: VideoBitrate;
  videoCodec: VideoCodec;
  videoResolution: VideoResolution;
}
