import {
  CAPTURE_SOURCES_ACTION_TOGGLE_AUDIO_CAPTURE_SOURCE,
  CAPTURE_SOURCES_ACTION_TOGGLE_CAMERA_CAPTURE_SOURCE,
  CAPTURE_SOURCES_ACTION_TOGGLE_CAMERA_DESKTOP_AUDIO_CAPTURE_SOURCE,
  CAPTURE_SOURCES_ACTION_TOGGLE_DESKTOP_AUDIO_CAPTURE_SOURCE,
  CAPTURE_SOURCES_ACTION_TOGGLE_DESKTOP_CAPTURE_SOURCE,
} from '_shared/constants';
import { Action } from 'redux';

export interface ToggleCaptureSourceAction extends Action {
  type:
    | typeof CAPTURE_SOURCES_ACTION_TOGGLE_AUDIO_CAPTURE_SOURCE
    | typeof CAPTURE_SOURCES_ACTION_TOGGLE_CAMERA_CAPTURE_SOURCE
    | typeof CAPTURE_SOURCES_ACTION_TOGGLE_DESKTOP_AUDIO_CAPTURE_SOURCE
    | typeof CAPTURE_SOURCES_ACTION_TOGGLE_DESKTOP_CAPTURE_SOURCE
    | typeof CAPTURE_SOURCES_ACTION_TOGGLE_CAMERA_DESKTOP_AUDIO_CAPTURE_SOURCE;
  payload: {
    enabled: boolean;
  };
}
