import { AudioBitrate, AudioProcessorType, BridgeMode, VideoBitrate, VideoCodec, VideoResolution } from '_shared/enums';
import { SettingsState } from '_shared/types';

export const settingsState: SettingsState = {
  allowUntrustedSSL: false,
  audioBitrate: AudioBitrate.Medium,
  audioProcessorControlsEnabled: false,
  audioProcessorIp: '',
  audioProcessorType: AudioProcessorType.Tendzone,
  autostartBroadcastsEnabled: false,
  bridgeMode: BridgeMode.Broadcast,
  broadcastsKey: '',
  broadcastsServer: '',
  communicationAuthenticationEnabled: false,
  communicationBridgeToken: '',
  communicationBridgeUrl: 'https://bridge.meet.aktru.video',
  communicationCameraEnabled: true,
  communicationMicrophoneEnabled: true,
  contentProtectionDisabled: false,
  daysToKeepData: 0,
  deleteAfterUpload: true,
  dualCamModeEnabled: false,
  kalturaTrustedCA: '',
  meetTrustedCA: '',
  mirrorCamera: false,
  moodleEnabled: false,
  moodlePlayerId: 0,
  moodleToken: '',
  moodleTrustedCA: '',
  moodleUrl: '',
  presenceControlEnabled: true,
  ptzCameraControlsEnabled: false,
  ptzCameraDefaultPresetIndex: 1,
  ptzCameraIp: '',
  reactivateSchedule: true,
  recordingPath: '',
  resetPtzCameraPreset: true,
  sakaiEnabled: false,
  sakaiLogin: '',
  sakaiPassword: '',
  sakaiTrustedCA: '',
  sakaiUrl: '',
  scheduleCommunicationEnabled: false,
  scheduleEnabled: false,
  scheduleRoomNumber: '',
  scheduleToken: '',
  scheduleTrustedCA: '',
  scheduleUrl: '',
  servicePartnerId: 0,
  servicePartnerSecret: '',
  serviceTokenId: '',
  serviceTokenSecret: '',
  serviceUrl: '',
  videoBitrate: VideoBitrate.High,
  videoCodec: VideoCodec.H264,
  videoResolution: VideoResolution.High,
};
