export enum Entitlement {
  CanCancelRecording = 'CAN_CANCEL_RECORDING',
  CanCaptureCamera = 'CAN_CAPTURE_CAMERA',
  CanCaptureDualCamera = 'CAN_CAPTURE_DUAL_CAMERA',
  CanCaptureDualDesktop = 'CAN_CAPTURE_DUAL_DESKTOP',
  CanCaptureMicrophone = 'CAN_CAPTURE_MICROPHONE',
  CanCaptureScreen = 'CAN_CAPTURE_SCREEN',
  CanCaptureSystemAudio = 'CAN_CAPTURE_SYSTEM_AUDIO',
  CanCaptureWindows = 'CAN_CAPTURE_WINDOWS',
  CanControlAudioProcessor = 'CAN_CONTROL_AUDIO_PROCESSOR',
  CanControlPtzCamera = 'CAN_CONTROL_PTZ_CAMERA',
  CanHotSwapCaptureSources = 'CAN_HOT_SWAP_CAPTURE_SOURCES',
  CanMuteAudio = 'CAN_MUTE_AUDIO',
  CanRecordDualChannel = 'CAN_RECORD_DUAL_CHANNEL',
  CanRecordFullHd = 'CAN_RECORD_FULL_HD',
  CanRecordOnDemand = 'CAN_RECORD_ON_DEMAND',
  CanRecordOnSchedule = 'CAN_RECORD_ON_SCHEDULE',
  CanRecordSingleChannel = 'CAN_RECORD_SINGLE_CHANNEL',
  CanRecordUltraHd = 'CAN_RECORD_ULTRA_HD',
  CanUseMeetBroadcasting = 'CAN_USE_MEET_BROADCASTING',
  CanUseMeetConferencing = 'CAN_USE_MEET_CONFERENCING',
  CanUseStreamDeck = 'CAN_USE_STREAM_DECK',
  HasEducationalMetadata = 'HAS_EDUCATIONAL_METADATA',
  HasKioskMode = 'HAS_KIOSK_MODE',
  HasScheduleReactivation = 'HAS_SCHEDULE_REACTIVATION',
  HasSystemAudioToggle = 'HAS_SYSTEM_AUDIO_TOGGLE',
  HasExpertSettings = 'HAS_EXPERT_SETTINGS',
}
