export enum ProcessEnvKey {
  COMMUNICATION_BRIDGE_URL = 'COMMUNICATION_BRIDGE_URL',
  COMMUNICATION_BRIDGE_TOKEN = 'COMMUNICATION_BRIDGE_TOKEN',
  SCHEDULE_ROOM_NUMBER = 'SCHEDULE_ROOM_NUMBER',
  SCHEDULE_TOKEN = 'SCHEDULE_TOKEN',
  SCHEDULE_URL = 'SCHEDULE_URL',
  MEET_TRUSTED_CA = 'MEET_TRUSTED_CA',
  SCHEDULE_TRUSTED_CA = 'SCHEDULE_TRUSTED_CA',
  ALLOW_UNTRUSTED_SSL = 'ALLOW_UNTRUSTED_SSL',
}
